### ISSUE TITLE
compiled .hex or .elf? ATTiny45 vs 85?

### ISSUE THREAD

**Issue by nabontra** [Petezah/roomba_wall_v3#2]
Thank you for sharing this great project! I built one this afternoon from your OSHpark link and am planning to flash the ATtiny tomorrow. I normally use an Atmel ICE programmer on Windows for my ATtiny chips, do you have a compiled .hex or .elf file that you can share in the repo? I used your firmware to create a build, but it was having trouble adapting the makefile from Linux.

You use ATTiny45 and ATTiny 85 in your repo, do you see one being better than the other for this application?

**Comment by Petezah** [comment]
@nabontra The design will work with either the ATTiny45 or the ATTiny85 (honestly, it is small enough to fit in the ATTiny25 also).  It uses the 45 in the most recent designs, because only the 45 has a TSSOP package (the latest designs use that smallest package).  The only difference between all these chips is flash size (2k vs 4k vs 8k).  Anyway, it is very WIP still, so I haven't gotten around to publishing any kind of build artifacts; but Atmel Studio should do the job, if that is your weapon of choice.  It uses AVR-GCC also.  Just make sure the clock speed is set to 8Mhz.  There's nothing really unusual about the build process.

**Comment by Petezah** [comment]
@nabontra I now have CI set up for the firmware, so you can should be able to follow the green checkmarks by any commit now and get the latest artifacts.  (see here for the latest, as of now: https://ci.appveyor.com/project/Petezah/roomba-wall-v3/build/1.0.6/artifacts )  I hope this helps you.
